version: "3.3"

services:
  app:
    image: "traefik/whoami"
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami.talvor.io`)
        - traefik.http.routers.whoami.entrypoints=websecure
        - traefik.http.services.whoami.loadbalancer.server.port=80
        - traefik.http.routers.whoami.service=whoami

networks:
  traefik-public:
    external: true