---
downloads: ~/.ansible-downloads/

# Nerd fonts
nf_user: "{{ ansible_env.USER }}"
nf_group: "{{ nf_user }}"
nf_single_fonts:
  - "FiraCode/Regular/FiraCodeNerdFont-Regular.ttf"
  - "FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf"
  - "JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFontMono-Regular.ttf"

# Install packages.
flatpak_packages:
  - name: com.brave.Browser
  - name: com.visualstudio.code

pip_packages:
  - name: psutil

deb_packages: []

apt_packages:
  - name: neofetch
  - name: htop
  - name: kitty

snap_packages: []

