---
downloads: ~/.ansible-downloads/

# Docker
docker_install_compose: false
docker_install_compose_plugin: true
docker_users: ["{{ ansible_env.USER }}"]

# Powerline fonts
powerline_fonts:
  - SourceCodePro

# Nerd fonts
nf_user: "{{ ansible_env.USER }}"
nf_group: "{{ nf_user }}"
nf_single_fonts:
  - "FiraCode/Regular/FiraCodeNerdFont-Regular.ttf"

# Install packages.
flatpak_packages: []
  # - name: com.visualstudio.code

pip_packages:
  - name: psutil

deb_packages:
  - name: "https://github.com/twpayne/chezmoi/releases/download/v2.34.0/chezmoi_2.34.0_linux_amd64.deb"
  - name: "https://az764295.vo.msecnd.net/stable/695af097c7bd098fbf017ce3ac85e09bbc5dda06/code_1.79.2-1686734195_amd64.deb"

apt_packages:
  - name: snapd
  - name: neofetch
  - name: alacritty
  - name: htop

snap_packages: []
  # - name: distrobox
  #   state: present
  #   channel: stable
