---
# ZSH
antigen_users:
  - username: "{{ ansible_env.USER }}"
    antigen_libraries:
      - name: oh-my-zsh
    antigen_theme:
      name: robbyrussell
    antigen_bundles:
      - name: command-not-found
      - name: git
      - name: nvm
      - name: kubectl
antigen_bundle_users:
  - username: "{{ ansible_env.USER }}"
    antigen_bundles:
      - name: zsh-completions
        url: zsh-users/zsh-completions
      - name: zsh-autosuggestions
        url: zsh-users/zsh-autosuggestions
      - name: zsh-syntax-highlighting
        url: zsh-users/zsh-syntax-highlighting

# Install packages.
flatpak_packages: []

pip_packages: []

deb_packages:
  - name: "https://az764295.vo.msecnd.net/stable/695af097c7bd098fbf017ce3ac85e09bbc5dda06/code_1.79.2-1686734195_amd64.deb"

apt_packages:
  - name: neofetch
  - name: htop

snap_packages: []
  # - name: distrobox
  #   state: present
  #   channel: stable
