---
roles:
  - name: gantsign.antigen
  - name: gantsign.antigen_bundles
  - name: geerlingguy.docker
  - name: sicruse.powerline-fonts
  - name: ctorgalson.nerdfonts
  - name: gantsign.golang
  - name: gantsign.helm

collections:
  - name: community.general
