---
- hosts: all

  vars:
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ lookup('env','USER') }}"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config_dev_container.yml"
      tags:
        - always
    - name: Set ansible_distribution to Ubuntu
      set_fact: ansible_distribution="Ubuntu"
      tags:
        - always

  roles:
    - role: gantsign.golang
      become: true
      golang_install_dir: /usr/local/go
      golang_gopath: "{{ lookup('env','HOME') }}/development/go"

    - role: gantsign.helm
      become: true

  tasks:
    - name: Create go development directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/development/go"
        state: directory
        mode: '0755'

    - name: Create node development directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/development/node"
        state: directory
        mode: '0755'

    - name: Create dotnet development directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/development/dotnet"
        state: directory
        mode: '0755'

    - name: Install nvm
      import_tasks: tasks/nvm.yml
      tags:
        - nvm

    - name: Install kubectl
      import_tasks: tasks/kubectl.yml
      become: true
      tags:
        - kubectl
        - k8s

    - name: Install packages
      import_tasks: tasks/packages.yml
      tags:
        - packages
