---
- hosts: all

  vars:
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ lookup('env','USER') }}"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config_dev_container.yml"
      tags:
        - always
    - name: Set ansible_distribution to Ubuntu
      set_fact: ansible_distribution="Ubuntu"
      tags:
        - always

  roles:
    - role: gantsign.antigen
      when: install_zsh
      become: true
      users: "{{antigen_users}}"
      tags:
        - zsh
        - antigen
        
    - role: gantsign.antigen_bundles
      when: install_zsh
      become: true
      users: "{{antigen_bundle_users}}"
      tags:
        - zsh
        - antigen_bundles
        
    - role: andrewrothstein.starship
      tags:
        - starship

  tasks:
    - name: Set .zshrc
      import_tasks: tasks/zshrc.yml
      tags:
        - zshrc
        - zsh
        
    - name: Install kubectl
      import_tasks: tasks/kubectl.yml
      become: true
      tags:
        - kubectl
        - k8s
        
    - name: Install packages
      import_tasks: tasks/packages.yml
      tags:
        - packages
