---
- name: Ensure Stow installed
  become: yes
  become_user: root
  apt:
    name: stow
    state: present

- name: Build directories list
  find:
    paths: [dotfiles/]
    recurse: no
    file_type: directory
  register: files

- name: Deploy dotfiles!
  become: yes
  become_user: '{{ local_user }}'
  with_items: '{{ files.files }}'
  shell: |
    STOW_PATH={{ item.path | replace("dotfiles/", "") }}
    OVERRIDE=$(cat ${STOW_PATH}/.override 2>/dev/null)
    USER_HOME={{ local_home }}
    stow -v --ignore="\.override" -t ${OVERRIDE:-$USER_HOME} ${STOW_PATH}
  args:
    chdir: ./dotfiles
    executable: /bin/bash
  loop_control:
    label: |-
      {% if output.stderr|length > 1 %}
      {{ item.path }}
      {{ output.stderr }}
      {%- else %}
      {{ item.path }}
      {%- endif %}
  register: output
  changed_when: '"LINK" in output.stderr'