---
- name: Install snap packages.
  become: yes
  become_user: root
  snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    channel: "{{ item.channel | default('stable') }}"
    classic: "{{ item.classic | default('false') }}"
  loop: "{{ snap_packages }}"