---
- name: Check for ssh key
  stat:
    path: "{{local_home}}/.ssh/id_ed25519"
  register: check_ssh_key

- name: Load ssh_key_vault
  include_vars:
    file: files/ssh_key_vault.yml
  when: not check_ssh_key.stat.exists

- name: Decode SSH Key
  shell: echo {{ssh_private_key}} |base64 --decode
  register: ssh_private_key_decoded
  when: not check_ssh_key.stat.exists

- name: Create id_ed25519 file
  template:
    src: templates/ssh/id_ed25519.t2
    dest: "{{local_home}}/.ssh/id_ed25519"
    owner: "{{local_user}}"
    group: "{{local_user}}"
    mode: '0600'
  when: not check_ssh_key.stat.exists

- name: Create id_ed25519.pub file
  template:
    src: templates/ssh/id_ed25519.pub.t2
    dest: "{{local_home}}/.ssh/id_ed25519.pub"
    owner: "{{local_user}}"
    group: "{{local_user}}"
    mode: '0644'
  when: not check_ssh_key.stat.exists

- name: Register SSH Key
  shell: ssh-add "{{local_home}}/.ssh/id_ed25519"
  when: not check_ssh_key.stat.exists
