apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.internal`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80