apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prometheus.internal`)
      kind: Rule
      services:
        - name: monitoring-prometheus-server
          port: 80